version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env.local:/app/.env.local
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
